# Generated by Django 2.1.4 on 2019-01-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidacy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leader", models.CharField(max_length=300)),
                ("party", models.CharField(max_length=300)),
                ("website", models.URLField()),
            ],
        )
    ]
