# Generated by Django 2.1.4 on 2019-01-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="candidacy",
            name="website",
            field=models.URLField(blank=True, null=True),
        )
    ]
