# Generated by Django 2.1.4 on 2019-01-06 00:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_auto_20190105_2154"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analytic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("path", models.CharField(blank=True, max_length=400, null=True)),
                (
                    "querystring",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
